version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "production"
      target-branch: "develop"
      labels:
          - "Composer updates by Dependabot"
