version: 2
updates:
    -
        package-ecosystem: composer
        directory: "/"
        schedule:
            interval: daily
            time: "10:00"
        versioning-strategy: increase-if-necessary
